### ISSUE TITLE
Fail to inject OKTA AD Connector

### ISSUE THREAD

**Issue by superboy-zjc** [xpn/CloudInject#1]
OS: Windows Server 2016
Okta AD Agent version: 3.17.0.0

I can manage to intercept the credential through x64dbg, while fail to do this by injecting the DLL
<img width="1511" alt="image" src="https://github.com/xpn/CloudInject/assets/60600792/f087e4c7-1542-4acf-a0c0-c28c1cddb969">
The way I compile the hooker and injector:
```
x86_64-w64-mingw32-g++.exe .\hooker\hooker.cpp -o
 .\Hooker\hooker.dll -static -shared
x86_64-w64-mingw32-g++.exe .\Injector\injector.cp
p -o .\Injector\injector.exe -static
```
Try to exploit, while nothing happen:
```
PS C:\Users\Administrator\Desktop\cloudinject\CloudInject-main> tasklist /FI  "IMAGENAME eq OKTA*"

Image Name                     PID Session Name        Session#    Mem Usage
========================= ======== ================ =========== ============
OktaAgentService.exe          6120 Services                   0     55,828 K
PS C:\Users\Administrator\Desktop\cloudinject\CloudInject-main> .\Injector\injector.exe 6120 .\Hooker\hooker.dll
```
<img width="1407" alt="image" src="https://github.com/xpn/CloudInject/assets/60600792/9a5769b7-9850-4cd0-a999-b50f4f4dbab2">

Could you advise me how to solve this?

**Comment by xpn** [comment]
The issue looks to be because you are passing in a relative path to the DLL to inject.

The injector writes in the path to the DLL (`.\Hooker\hooker.dll\0` is 20 bytes), and then within the `OktaAgentService.exe` it calls `LoadLibrary()`. So in this case it's going to do `LoadLibrary(".\Hooker.\hooker.dll")` which will fail because `OktaAgentService.exe` doesn't know the full path.

I'll update the documentation, but for fixing this, move hooker.dll to a shared directory that OktaAgentService.exe can open, so `C:\Tools\Hooker.dll` for example, and then pass the full path to `injector.exe`, so `injector.exe 6120 C:\Tools\Hoooker.dll`.

You can also make sure that the DLL is loaded using ProcessExplorer or SystemInformer.

**Comment by xpn** [comment]
Updated the README.md with an example: https://github.com/xpn/CloudInject/blob/main/README.md

**Comment by superboy-zjc** [comment]
Oh! it works now! Thanks for your help!
<img width="1288" alt="image" src="https://github.com/xpn/CloudInject/assets/60600792/44e6d0ea-d721-43fc-ae74-5a21a5c67b7e">

**Comment by xpn** [comment]
Thanks for confirming 🙏
